=== wieslawsoltes/WebScene/tooling/htmlml/schemas/htmlml-interop-policy.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "HtmlML JavaScript interop policy",
  "type": "object",
  "required": [
    "schemaVersion",
    "api",
    "namespace",
    "bindings"
  ],
  "properties": {
    "schemaVersion": {
      "const": "1.0"
    },
    "api": {
      "type": "string",
      "minLength": 1
    },
    "apiFingerprint": {
      "type": "string",
      "pattern": "^[0-9a-f]{64}$"
    },
    "namespace": {
      "type": "string",
      "pattern": "^[A-Za-z_][A-Za-z0-9_.]*$"
    },
    "typeMappings": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "minLength": 1
      }
    },
    "functionsClassName": {
      "type": "string",
      "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
    },
    "functions": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/function"
      }
    },
    "globalProperties": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/globalProperty"
      }
    },
    "models": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/model"
      }
    },
    "adapters": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/adapter"
      }
    },
    "bindings": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/binding"
      }
    }
  },
  "additionalProperties": false,
  "$defs": {
    "function": {
      "type": "object",
      "required": [
        "source",
        "globalName"
      ],
      "properties": {
        "source": {
          "type": "string",
          "minLength": 1
        },
        "globalName": {
          "type": "string",
          "minLength": 1
        },
        "overload": {
          "type": "integer",
          "minimum": 0
        },
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        },
        "include": {
          "type": "boolean"
        },
        "omitOptionalParameters": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "globalProperty": {
      "type": "object",
      "required": [
        "source",
        "globalName"
      ],
      "properties": {
        "source": {
          "type": "string",
          "minLength": 1
        },
        "globalName": {
          "type": "string",
          "minLength": 1
        },
        "getterName": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        },
        "include": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "model": {
      "type": "object",
      "required": [
        "source"
      ],
      "properties": {
        "source": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        },
        "include": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "adapter": {
      "type": "object",
      "required": [
        "source",
        "name"
      ],
      "properties": {
        "source": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        },
        "include": {
          "type": "boolean"
        },
        "methods": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/method"
          }
        }
      },
      "additionalProperties": false
    },
    "binding": {
      "type": "object",
      "required": [
        "source",
        "name",
        "methods"
      ],
      "properties": {
        "source": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        },
        "include": {
          "type": "boolean"
        },
        "constructor": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/$defs/constructor"
            }
          ]
        },
        "constructors": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/constructor"
          }
        },
        "methods": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/method"
          }
        },
        "properties": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/property"
          }
        }
      },
      "additionalProperties": false
    },
    "constructor": {
      "type": "object",
      "required": [
        "globalName"
      ],
      "properties": {
        "globalName": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        },
        "overload": {
          "type": "integer",
          "minimum": 0
        },
        "parameters": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "name",
              "dotnetType"
            ],
            "properties": {
              "name": {
                "type": "string",
                "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
              },
              "dotnetType": {
                "type": "string",
                "minLength": 1
              }
            },
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    },
    "method": {
      "type": "object",
      "required": [
        "source"
      ],
      "properties": {
        "source": {
          "type": "string",
          "minLength": 1
        },
        "overload": {
          "type": "integer",
          "minimum": 0
        },
        "name": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        },
        "include": {
          "type": "boolean"
        },
        "omitOptionalParameters": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "property": {
      "type": "object",
      "required": [
        "source"
      ],
      "properties": {
        "source": {
          "type": "string",
          "minLength": 1
        },
        "include": {
          "type": "boolean"
        },
        "getterName": {
          "type": "string",
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        },
        "setterName": {
          "type": [
            "string",
            "null"
          ],
          "pattern": "^[A-Za-z_][A-Za-z0-9_]*$"
        },
        "write": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    }
  }
}

=== wieslawsoltes/WebScene/samples/TradingViewInterop.Generated/TradingView.webscene-interop-policy.json
{
  "schemaVersion": "1.0",
  "api": "TradingViewApi.webscene-interop-api.json",
  "apiFingerprint": "55f0efb59a9f2a7e4925675fac135764ae9ca540abde30a39e769498f9e5d525",
  "namespace": "TradingViewInterop.Generated",
  "typeMappings": {},
  "models": [
    {
      "source": "Charting_Library.ResolutionString",
      "name": "ResolutionString"
    },
    {
      "source": "Charting_Library.ChartingLibraryWidgetOptions",
      "name": "TradingViewWidgetOptions"
    },
    {
      "source": "Charting_Library.SetSymbolOptions",
      "name": "SetSymbolOptions"
    },
    {
      "source": "Datafeed.DatafeedConfiguration",
      "name": "DatafeedConfiguration"
    },
    {
      "source": "Datafeed.Exchange",
      "name": "Exchange"
    },
    {
      "source": "Datafeed.LibrarySymbolInfo",
      "name": "LibrarySymbolInfo"
    },
    {
      "source": "Datafeed.PeriodParams",
      "name": "PeriodParams"
    },
    {
      "source": "Datafeed.Bar",
      "name": "Bar"
    },
    {
      "source": "Datafeed.HistoryMetadata",
      "name": "HistoryMetadata"
    },
    {
      "source": "Datafeed.SearchSymbolResultItem",
      "name": "SearchSymbolResultItem"
    },
    {
      "source": "Datafeed.QuoteData",
      "name": "QuoteData"
    },
    {
      "source": "Broker.Order",
      "name": "Order"
    },
    {
      "source": "Broker.OrderStatus",
      "name": "OrderStatus"
    },
    {
      "source": "Broker.Side",
      "name": "Side"
    },
    {
      "source": "Broker.Position",
      "name": "Position"
    },
    {
      "source": "Broker.Execution",
      "name": "Execution"
    },
    {
      "source": "Broker.PreOrder",
      "name": "PreOrder"
    },
    {
      "source": "Broker.OrderResult",
      "name": "OrderResult"
    },
    {
      "source": "Broker.AccountManagerInfo",
      "name": "AccountManagerInfo"
    }
  ],
  "adapters": [
    {
      "source": "Datafeed.IDatafeedChartApi",
      "name": "TradingViewDatafeed"
    },
    {
      "source": "Broker.IBrokerTerminal",
      "name": "TradingViewBroker"
    }
  ],
  "bindings": [
    {
      "source": "Charting_Library.widget",
      "name": "TradingViewWidget",
      "constructor": {
        "globalName": "TradingView.widget",
        "name": "CreateAsync"
      },
      "methods": [
        {
          "source": "activeChart"
        },
        {
          "source": "getLanguage"
        },
        {
          "source": "remove"
        }
      ]
    },
    {
      "source": "Charting_Library.IChartWidgetApi",
      "name": "TradingViewChart",
      "constructor": null,
      "methods": [
        {
          "source": "symbol"
        },
        {
          "source": "resolution"
        },
        {
          "source": "setScrollEnabled"
        },
        {
          "source": "setZoomEnabled"
        },
        {
          "source": "setSymbol",
          "omitOptionalParameters": false
        },
        {
          "source": "createOrderLine"
        },
        {
          "source": "createPositionLine"
        },
        {
          "source": "createExecutionShape"
        },
        {
          "source": "crosshairPrice"
        },
        {
          "source": "setVisibleStudies"
        }
      ]
    },
    {
      "source": "Charting_Library.IWatchedValue",
      "name": "TradingViewWatchedValue",
      "constructor": null,
      "methods": [
        {
          "source": "value"
        },
        {
          "source": "setValue"
        },
        {
          "source": "subscribe"
        }
      ]
    },
    {
      "source": "Broker.IBrokerConnectionAdapterHost",
      "name": "TradingViewBrokerHost",
      "constructor": null,
      "methods": [
        {
          "source": "orderUpdate"
        },
        {
          "source": "positionUpdate"
        },
        {
          "source": "executionUpdate"
        },
        {
          "source": "showNotification",
          "omitOptionalParameters": false
        }
      ]
    },
    {
      "source": "Charting_Library.IOrderLineAdapter",
      "name": "TradingViewOrderLine",
      "constructor": null,
      "properties": [
        {
          "source": "id"
        },
        {
          "source": "price",
          "setterName": "SetPricePropertyAsync"
        }
      ],
      "methods": [
        {
          "source": "setPrice"
        },
        {
          "source": "setQuantity"
        },
        {
          "source": "setText"
        },
        {
          "source": "remove"
        }
      ]
    },
    {
      "source": "Charting_Library.IPositionLineAdapter",
      "name": "TradingViewPositionLine",
      "constructor": null,
      "methods": [
        {
          "source": "setPrice"
        },
        {
          "source": "setQuantity"
        },
        {
          "source": "setText"
        },
        {
          "source": "remove"
        }
      ]
    },
    {
      "source": "Charting_Library.IExecutionLineAdapter",
      "name": "TradingViewExecutionLine",
      "constructor": null,
      "methods": [
        {
          "source": "setPrice"
        },
        {
          "source": "setQuantity"
        },
        {
          "source": "setText"
        },
        {
          "source": "setTime"
        },
        {
          "source": "remove"
        }
      ]
    }
  ]
}

=== wieslawsoltes/WebScene/samples/NativeRuntimeShowcase.Interop/Monaco.htmlml-interop-policy.json
{
  "schemaVersion": "1.0",
  "api": "MonacoApi.htmlml-interop-api.json",
  "apiFingerprint": "b3c15b8dfa5ee2213705a6008c719cd05ab771a25def7de65f0054229d359be8",
  "namespace": "NativeRuntimeShowcase.Interop",
  "typeMappings": {},
  "functionsClassName": "MonacoApi",
  "functions": [
    {
      "source": "monaco.editor.setModelLanguage",
      "overload": 0,
      "globalName": "monaco.editor.setModelLanguage",
      "name": "SetModelLanguageAsync",
      "include": true,
      "omitOptionalParameters": false
    }
  ],
  "globalProperties": [],
  "models": [],
  "adapters": [
    {
      "source": "monaco.editor.IStandaloneCodeEditor",
      "name": "StandaloneCodeEditorAdapter",
      "include": false,
      "methods": [
        {
          "source": "focus",
          "overload": 0,
          "name": "FocusAsync",
          "include": false
        },
        {
          "source": "getModel",
          "overload": 0,
          "name": "GetModel",
          "include": false
        },
        {
          "source": "getValue",
          "overload": 0,
          "name": "GetValue",
          "include": false
        },
        {
          "source": "layout",
          "overload": 0,
          "name": "LayoutAsync",
          "include": false
        },
        {
          "source": "setValue",
          "overload": 0,
          "name": "SetValueAsync",
          "include": false
        }
      ]
    },
    {
      "source": "monaco.editor.ITextModel",
      "name": "TextModelAdapter",
      "include": false,
      "methods": [
        {
          "source": "getValue",
          "overload": 0,
          "name": "GetValue",
          "include": false
        },
        {
          "source": "setValue",
          "overload": 0,
          "name": "SetValueAsync",
          "include": false
        }
      ]
    }
  ],
  "bindings": [
    {
      "source": "monaco.editor.IStandaloneCodeEditor",
      "name": "MonacoEditor",
      "include": true,
      "constructor": null,
      "constructors": [],
      "properties": [],
      "methods": [
        {
          "source": "focus",
          "overload": 0,
          "name": "FocusAsync",
          "include": true,
          "omitOptionalParameters": false
        },
        {
          "source": "getModel",
          "overload": 0,
          "name": "GetModelAsync",
          "include": true,
          "omitOptionalParameters": false
        },
        {
          "source": "getValue",
          "overload": 0,
          "name": "GetValueAsync",
          "include": true,
          "omitOptionalParameters": false
        },
        {
          "source": "layout",
          "overload": 0,
          "name": "LayoutAsync",
          "include": true,
          "omitOptionalParameters": false
        },
        {
          "source": "setValue",
          "overload": 0,
          "name": "SetValueAsync",
          "include": true,
          "omitOptionalParameters": false
        }
      ]
    },
    {
      "source": "monaco.editor.ITextModel",
      "name": "MonacoTextModel",
      "include": true,
      "constructor": null,
      "constructors": [],
      "properties": [],
      "methods": [
        {
          "source": "getValue",
          "overload": 0,
          "name": "GetValueAsync",
          "include": true,
          "omitOptionalParameters": false
        },
        {
          "source": "setValue",
          "overload": 0,
          "name": "SetValueAsync",
          "include": true,
          "omitOptionalParameters": false
        }
      ]
    }
  ]
}
